сделала по классам и создала функцию renderFilm
htmlacademy-ecmascript/483923-cinemaddict-16 pull request #5
Opened 2021-12-11 15:41 UTC by Lara87

2021-12-12 21:22 UTC, ArtemVeremienko requested changes
Молодец, создала классы с правильной структурой!

Все функции по типу `createTemplate` нужно поместить внутрь класса, теперь это будет просто метод `template`. Если нужны данные для создания элемента, то мы их берём с приватных свойств, в который помещаем при создании объекта (в конструкторе)

И проверь `z-index` карточек фильмов при открытой модалке.

2021-12-12 21:22 UTC, ArtemVeremienko commented on src/view/btn-show-more.js
> +const createBtnShowMoreTemplate = () => '<button class="films-list__show-more">Show more</button>';
Логику этой функции и других подобных лучше перенести в сам класс с элементом, потому что они к нему относятся. Это будет в гетере `template`

2021-12-12 21:22 UTC, ArtemVeremienko commented on src/render.js
> +  return newElement.firstChild;//получили готовый дом элемент и вернули первый дочерний элемент (без нашей обертки)
Для чего нам эта функция? Что она делает? 🤔

2021-12-12 21:22 UTC, ArtemVeremienko commented on src/view/comment-view.js
> +};
Эта функция также будет в `template`, только все значения комментариев мы будем получать с приватного свойства объекта (поместим в него при создании).

2021-12-12 21:22 UTC, ArtemVeremienko commented on src/main.js
> +render(footerStatisticsElement, new StatisticsView().element, RenderPosition.BEFOREEND);
Создание компонентов лучше присваивать переменной, они могут нам пригодиться в будущем
```suggestion
const staticView = new StaticView();
render(footerStatisticsElement, staticView.element, RenderPosition.BEFOREEND);
```

2021-12-13 19:20 UTC, Lara87 commented on src/render.js
> +  return newElement.firstChild;//получили готовый дом элемент и вернули первый дочерний элемент (без нашей обертки)
принимает разметку и из неё создает DOM элемент и возвращает нам наш компонент

2021-12-14 12:13 UTC, ArtemVeremienko requested changes
Давай внесём минимальные изменения и всё будет готово)

2021-12-14 12:13 UTC, ArtemVeremienko commented on src/view/btn-show-more.js
>    }
Можно упростить и сразу вернуть темплейнт
```js
get template() {
  return '<button class="films-list__show-more">Show more</button>';
}
```

2021-12-14 12:13 UTC, ArtemVeremienko commented on src/view/btn-show-more.js
>    }
Попробуй так сделать для всех остальных компонентов. Твой способ рабочий, но не совсем понятно зачем мы в гетере создаём функцию которую выполняем один раз в результате гетера :wink

2021-12-14 18:54 UTC, ArtemVeremienko approved these changes

2021-12-14 18:55 UTC, merged