Разделяй и властвуй
htmlacademy-ecmascript/483923-cinemaddict-16 pull request #6
Opened 2021-12-14 20:48 UTC by Lara87

…дование всем компонентам, реализовала подписку внутри компонентов

---
:mortar_board: [Разделяй и властвуй](https://up.htmlacademy.ru/ecmascript/16/user/483923/tasks/7)

:boom: https://htmlacademy-ecmascript.github.io/483923-cinemaddict-16/6/

2021-12-16 23:09 UTC, ArtemVeremienko requested changes

2021-12-16 23:11 UTC, ArtemVeremienko commented
Всё отлично отрефакторила 😉

2021-12-18 16:00 UTC, Lara87 commented on src/view/abstract-view.js
> +  _callback = {};
защищённый можно использовать в  дочерних классах, а т.к. в нескольких компонентах требуется подписка/отписка на событие, то можно работать с _callback в классах-наследниках, будем потом в это защищённое свойство сохранять ссылку на функцию коллбэк. А приватное свойство используется только внутри класса, снаружи не обратиться к нему.

2021-12-18 16:02 UTC, Lara87 commented on src/view/abstract-view.js
> +  _callback = {};
мы потом делаем this._callback.anyClick = callback; т.е. непосредственно работаем со свойством.

2021-12-18 19:02 UTC, ArtemVeremienko commented on src/view/abstract-view.js
> +  _callback = {};
Хорошо, молодец 😉

2021-12-18 19:02 UTC, merged