добавление описания презентера доски с фильмами
htmlacademy-ecmascript/483923-cinemaddict-16 pull request #7
Opened 2021-12-19 14:08 UTC by Lara87

2022-01-10 19:59 UTC, ArtemVeremienko requested changes
Сейчас интересная логика при открытии попапа. Когда мы нажимаем на фильм он отображается в попапе, но пропадает со списка фильмов. Этого не должно быть.

Логика попапа находится в презентере каждого фильма, его лучше вынести в призентер списка фильмов, потому что он у нас один. У него просто есть 2 режима - открытый и закрытый и отображает фильм который ему передаем.

Уточню подсказки с задания:
1. Добавьте в презентер метод для скрытия попапа. _(в перезентер списка фильмов)_
2. Передайте в презентер фильма колбэк, который нужно вызвать перед тем, как открыть новый попап. _(при клике на фильм будем вызывать этот колбэк)_
3. В презентере списка фильмов реализуйте метод для этого колбэка, который скроет попап, если таковой уже открыт. _(сама логика попапа в презентере списка фильмов)_

2022-01-10 19:59 UTC, ArtemVeremienko commented on src/presenter/movie-presenter.js
> +  }
Вотчлист не работает корректно из-за ошибки в нейминге свойства `isWatchlist`, это функция изменяет свойство `isWatchList`. Попробуй исправить на
```suggestion
  #handleWatchlist = () => {
    this.#changeData({...this.#film, isWatchlist: !this.#film.isWatchlist});
  }
```

2022-01-10 19:59 UTC, ArtemVeremienko commented
> Сейчас интересная логика при открытии попапа. Когда мы нажимаем на фильм он отображается в попапе, но пропадает со списка фильмов. Этого не должно быть.
> 
> Логика попапа находится в презентере каждого фильма, его лучше вынести в призентер списка фильмов, потому что он у нас один. У него просто есть 2 режима - открытый и закрытый и отображает фильм который ему передаем.
> 
> Уточню подсказки с задания:
> 
> 1. Добавьте в презентер метод для скрытия попапа. _(в перезентер списка фильмов)_
> 2. Передайте в презентер фильма колбэк, который нужно вызвать перед тем, как открыть новый попап. _(при клике на фильм будем вызывать этот колбэк)_
> 3. В презентере списка фильмов реализуйте метод для этого колбэка, который скроет попап, если таковой уже открыт. _(сама логика попапа в презентере списка фильмов)_

2022-01-12 22:45 UTC, ArtemVeremienko commented
@Lara87 текущий статус:
1. Не увидел вынесение логики попапа в `movie-list-presenter.js`. В данной версии эта логика находится в презентере каждого фильма.
2. При добавлении фильма в список watchlist/watched/favorite в попапе фильм удаляется со списка фильмов на странице.
3. Уточни,пожалуйста, где у тебя происходит ошибка `Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`. Я так понимаю это связано с попапом. (Лучше ошибку копировать полность вместе с указанием файла с линии с ошибкой)

Лучше начать с первого пункта, так как он связан со вторым и третим.

2022-01-20 18:56 UTC, ArtemVeremienko approved these changes
Получилось вынести попап в презентер списка, молодец! 😉 

Логика попапа осталась похожая как в прошлом варианте, он добавляется или удаляется при клике на карточку с фильмом. 
Нам нужно сделать чтобы он именно отображался или скрывался. То есть мы его будем добавлять только один раз. Можешь его попробовать вынести с отдельный презентер, возможно так будет проще всё разграничить,

2022-01-20 18:56 UTC, ArtemVeremienko commented on src/presenter/movie-list-presenter.js
> +      scrollTop = this.#filmPopupComponent.element.scrollTop;
здесь `scrollTop` всегда будет 0, потому что перед открытием попапа мы его удаляем.

2022-01-20 18:56 UTC, ArtemVeremienko commented on src/presenter/movie-presenter.js
> +    this.#prevFilmCardComponent = this.#filmComponent;
Для чего нам знать предыдущий компонент с фильмом?

2022-01-20 18:59 UTC, merged

2022-01-22 19:06 UTC, Lara87 commented on src/presenter/movie-presenter.js
> +    this.#prevFilmCardComponent = this.#filmComponent;
чтобы можно было переиспользовать, мы запоминаем предыдущий, а потом мы проверяем, если предыдущего нет, то рисуем как обычно, а иначе мы делаем замену.